name: GigEVirtualCamera
options:
  bundleIdPrefix: com.lukechang
  deploymentTarget:
    macOS: "12.3"
  developmentLanguage: en
  createIntermediateGroups: true
  generateEmptyDirectories: true
  
settings:
  # Team ID can be overridden via environment variable APPLE_TEAM_ID
  # Default is maintained for convenience, but CI/CD will use secrets
  DEVELOPMENT_TEAM: S368GH6KF7
  # Build for Apple Silicon only (Aravis is arm64 only)
  ARCHS: arm64
  ONLY_ACTIVE_ARCH: NO
  # Aravis settings
  HEADER_SEARCH_PATHS: 
    - /opt/homebrew/include
    - /opt/homebrew/Cellar/aravis/0.8.35/include/aravis-0.8
    - /opt/homebrew/Cellar/glib/2.84.3/include
    - /opt/homebrew/Cellar/glib/2.84.3/include/glib-2.0
    - /opt/homebrew/Cellar/glib/2.84.3/lib/glib-2.0/include
    - /opt/homebrew/opt/gettext/include
    - /opt/homebrew/Cellar/pcre2/10.45/include
    - /Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk/usr/include/ffi
  LIBRARY_SEARCH_PATHS:
    - /opt/homebrew/lib
    - /opt/homebrew/Cellar/aravis/0.8.35/lib
  OTHER_LDFLAGS:
    - -laravis-0.8
    - -lgio-2.0
    - -lgobject-2.0
    - -lglib-2.0
    - -ObjC
    - -all_load
  
targets:
  GigEVirtualCamera:
    type: application
    platform: macOS
    sources:
      - GigECameraApp
      - path: Shared
        excludes:
          # Uncomment to use stub implementation
          # - "*.mm"
          # - "*.h"
          # Comment out to use real Aravis implementation
          - "AravisBridge-Stub.swift"
    dependencies:
      - target: GigECameraExtension
        embed: true
        codeSign: true
        embedInSubfolder: Library/SystemExtensions
      - sdk: SystemExtensions.framework
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.lukechang.GigEVirtualCamera
      INFOPLIST_FILE: GigECameraApp/Info.plist
      CODE_SIGN_ENTITLEMENTS: GigECameraApp/GigECamera.entitlements
      SWIFT_VERSION: 5.0
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
      SWIFT_OBJC_BRIDGING_HEADER: GigECameraApp/GigEVirtualCamera-Bridging-Header.h
      OTHER_LDFLAGS: $(inherited)
      ENABLE_HARDENED_RUNTIME: YES
      INFOPLIST_KEY_NSSystemExtensionInstallationPrompt: "GigE Virtual Camera needs to install a system extension to provide virtual camera functionality."
    configSettings:
      Debug:
        CODE_SIGN_ENTITLEMENTS: GigECameraApp/GigECamera-Debug.entitlements
        PROVISIONING_PROFILE_SPECIFIER: "GigE Virtual Camera Dev"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: S368GH6KF7
        CODE_SIGN_IDENTITY: "Apple Development"
      Release:
        CODE_SIGN_ENTITLEMENTS: GigECameraApp/GigECamera-Release.entitlements
        PROVISIONING_PROFILE_SPECIFIER: ""
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: S368GH6KF7
        # Generic identity - Xcode will select the right cert based on Team ID
        CODE_SIGN_IDENTITY: "Developer ID Application"
    preBuildScripts:
      - script: |
          if [ -d "${SRCROOT}/Scripts" ]; then
            chmod +x "${SRCROOT}/Scripts/"*.sh
          fi
        name: Make Scripts Executable
        basedOnDependencyAnalysis: false
    postBuildScripts:
      - script: |
          if [ "${CONFIGURATION}" = "Debug" ] || [ "${CONFIGURATION}" = "Release" ]; then
            "${SRCROOT}/Scripts/bundle_aravis.sh" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app"
            "${SRCROOT}/Scripts/fix_rpaths.sh" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app"
            
            # Libraries will be signed by Xcode as part of the app bundle
            echo "Libraries bundled successfully"
          fi
        name: Bundle Aravis Libraries
        basedOnDependencyAnalysis: false
      - script: |
          # Copy app to /Applications for System Extension activation
          if [ "${CONFIGURATION}" = "Debug" ] || [ "${CONFIGURATION}" = "Release" ]; then
            echo "Copying app to /Applications..."
            rm -rf "/Applications/${PRODUCT_NAME}.app" 2>/dev/null || true
            # Use ditto to preserve code signatures and extended attributes
            ditto "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app" "/Applications/${PRODUCT_NAME}.app"
            echo "App copied to /Applications/${PRODUCT_NAME}.app"
            
            # Fix extension naming in /Applications
            if [ -d "/Applications/${PRODUCT_NAME}.app/Contents/Library/SystemExtensions/GigECameraExtension.systemextension" ]; then
              echo "Fixing extension naming..."
              mv "/Applications/${PRODUCT_NAME}.app/Contents/Library/SystemExtensions/GigECameraExtension.systemextension" \
                 "/Applications/${PRODUCT_NAME}.app/Contents/Library/SystemExtensions/com.lukechang.GigEVirtualCamera.Extension.systemextension"
              
              # Just copy without re-signing - let Xcode handle the signing
              echo "App copied successfully"
            fi
            
            # Remove provisioning profile for Release builds (Developer ID doesn't use them)
            if [ "${CONFIGURATION}" = "Release" ]; then
              echo "Removing provisioning profile for Developer ID distribution..."
              rm -f "/Applications/${PRODUCT_NAME}.app/Contents/embedded.provisionprofile" 2>/dev/null || true
              rm -f "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/Contents/embedded.provisionprofile" 2>/dev/null || true
            fi
          fi
        name: Copy to Applications
        basedOnDependencyAnalysis: false
      - script: |
          # Only run distribution steps if this is a Distribution build
          # Check if we're in the Distribution scheme by looking for a marker file
          if [ "${CONFIGURATION}" = "Release" ] && [ -f "${SRCROOT}/.distribution_build" ]; then
            echo "🚀 Starting distribution process..."
            
            # Ensure scripts are executable
            chmod +x "${SRCROOT}/Scripts/notarize.sh"
            chmod +x "${SRCROOT}/Scripts/create_dmg.sh"
            
            # Wait a moment for the app to be fully written
            sleep 2
            
            # Step 1: Notarize the app
            echo "📝 Notarizing app..."
            if "${SRCROOT}/Scripts/notarize.sh" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app"; then
              echo "✅ App notarized successfully"
            else
              echo "❌ Notarization failed"
              exit 1
            fi
            
            # Step 2: Create DMG
            echo "💿 Creating DMG..."
            if "${SRCROOT}/Scripts/create_dmg.sh" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app"; then
              echo "✅ DMG created successfully"
              
              # Step 3: Notarize the DMG
              echo "📝 Notarizing DMG..."
              DMG_PATH="${SRCROOT}/build/distribution/GigEVirtualCamera.dmg"
              
              if xcrun notarytool submit "$DMG_PATH" --keychain-profile "GigE-Notarization" --wait; then
                echo "✅ DMG notarized successfully"
                
                # Staple the notarization ticket
                if xcrun stapler staple "$DMG_PATH"; then
                  echo "✅ Notarization ticket stapled to DMG"
                  echo "🎉 Distribution build complete!"
                  echo "📦 DMG location: $DMG_PATH"
                  
                  # Open the distribution folder
                  open "${SRCROOT}/build/distribution"
                else
                  echo "❌ Failed to staple notarization ticket"
                  exit 1
                fi
              else
                echo "❌ DMG notarization failed"
                exit 1
              fi
            else
              echo "❌ DMG creation failed"
              exit 1
            fi
            
            # Clean up marker file
            rm -f "${SRCROOT}/.distribution_build"
          else
            echo "ℹ️  Skipping distribution steps (not a distribution build)"
          fi
        name: Distribution Steps
        basedOnDependencyAnalysis: false
          
  GigECameraExtension:
    type: system-extension
    platform: macOS
    sources:
      - path: GigEVirtualCameraExtension
        excludes:
          - GigEVirtualCameraExtensionProvider_OLD.swift
      - path: Shared
        excludes:
          - "AravisBridge-Stub.swift"
          - "AravisBridge.mm"
          - "AravisBridge.h"
          - "GigEVirtualCamera-Bridging-Header.h"
          - "GigECameraManager.swift"
          - "XPCFrameSender.swift"  # This is app-only, not extension
          - "TestCameraGenerator.swift"  # This is app-only, not extension
          - "IOSurfaceFrameSharing.swift"  # Not used with CMIO
          - "SharedMemoryFrameSharing.swift"  # Not used with CMIO
          - "CameraConstants.swift"  # App-only
          - "DesignSystem.swift"  # App-only
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.lukechang.GigEVirtualCamera.Extension
      PRODUCT_BUNDLE_PACKAGE_TYPE: SYSX
      SKIP_INSTALL: YES
      INFOPLIST_FILE: GigEVirtualCameraExtension/Info.plist
      CODE_SIGN_ENTITLEMENTS: GigEVirtualCameraExtension/GigEVirtualCameraExtension.entitlements
      SWIFT_VERSION: 5.0
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
      # Remove bridging header for extension
      # SWIFT_OBJC_BRIDGING_HEADER: Shared/GigEVirtualCamera-Bridging-Header.h
      # Override global settings to remove Aravis dependencies
      HEADER_SEARCH_PATHS: []
      LIBRARY_SEARCH_PATHS: []
      OTHER_LDFLAGS: -ObjC
    configSettings:
      Debug:
        CODE_SIGN_ENTITLEMENTS: GigEVirtualCameraExtension/GigEVirtualCameraExtension.entitlements
        PROVISIONING_PROFILE_SPECIFIER: "GigE Camera Extension Dev"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: S368GH6KF7
        CODE_SIGN_IDENTITY: "Apple Development"
      Release:
        CODE_SIGN_ENTITLEMENTS: GigEVirtualCameraExtension/GigEVirtualCameraExtension.entitlements
        PROVISIONING_PROFILE_SPECIFIER: ""
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: S368GH6KF7
        # Generic identity - Xcode will select the right cert based on Team ID
        CODE_SIGN_IDENTITY: "Developer ID Application"
    postBuildScripts:
      - script: |
          # The extension folder must match the bundle ID for sysextd to find it
          echo "Extension will be embedded with correct name by main app target"
        name: Extension Build Info
        basedOnDependencyAnalysis: false

schemes:
  GigEVirtualCamera:
    build:
      targets:
        GigEVirtualCamera: all
        GigECameraExtension: all
    run:
      config: Debug
      executable: GigEVirtualCamera
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  
  GigEVirtualCamera-Distribution:
    build:
      targets:
        GigEVirtualCamera: all
        GigECameraExtension: all
      preActions:
        - script: |
            # Create marker file to trigger distribution steps
            touch "${SRCROOT}/.distribution_build"
          settingsTarget: GigEVirtualCamera
    run:
      config: Release
      executable: GigEVirtualCamera
    test:
      config: Release
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release
      customArchiveName: GigEVirtualCamera-Distribution
      postActions:
        - script: |
            echo "Distribution archive created"
          settingsTarget: GigEVirtualCamera