#!/bin/bash

echo "Apple Developer Portal Setup for System Extensions"
echo "================================================="
echo ""
echo "Please follow these steps in your browser:"
echo ""
echo "1. Go to: https://developer.apple.com/account/resources/identifiers/list"
echo ""
echo "2. Create App ID for Main App:"
echo "   - Click '+' button"
echo "   - Select 'App IDs' → Continue"
echo "   - Select 'App' → Continue"
echo "   - Description: GigE Virtual Camera"
echo "   - Bundle ID: Explicit → com.lukechang.GigEVirtualCamera"
echo "   - Scroll down to Capabilities"
echo "   - ✓ Check 'System Extension'"
echo "   - Register"
echo ""
echo "3. Create App ID for Extension:"
echo "   - Click '+' button again"
echo "   - Select 'App IDs' → Continue"
echo "   - Select 'App' → Continue"
echo "   - Description: GigE Camera Extension"
echo "   - Bundle ID: Explicit → com.lukechang.GigEVirtualCamera.Extension"
echo "   - Register"
echo ""
echo "Press Enter when you've completed the App IDs..."
read

echo ""
echo "4. Go to: https://developer.apple.com/account/resources/profiles/list"
echo ""
echo "5. Create Profile for Main App:"
echo "   - Click '+' button"
echo "   - Select 'macOS App Development' → Continue"
echo "   - App ID: Select 'GigE Virtual Camera' → Continue"
echo "   - Select your certificate → Continue"
echo "   - Profile Name: GigE Virtual Camera Dev"
echo "   - Generate"
echo "   - Download the .provisionprofile file"
echo ""
echo "6. Create Profile for Extension:"
echo "   - Click '+' button"
echo "   - Select 'macOS App Development' → Continue"
echo "   - App ID: Select 'GigE Camera Extension' → Continue"
echo "   - Select your certificate → Continue"
echo "   - Profile Name: GigE Camera Extension Dev"
echo "   - Generate"
echo "   - Download the .provisionprofile file"
echo ""
echo "Press Enter when you've downloaded both profiles..."
read

echo ""
echo "7. Install the profiles:"
echo "   - Double-click each downloaded .provisionprofile file"
echo "   - They will install into Xcode automatically"
echo ""
echo "Press Enter when profiles are installed..."
read

echo ""
echo "8. Open Xcode:"
open GigEVirtualCamera.xcodeproj

echo ""
echo "9. In Xcode:"
echo "   - Select the project in the navigator"
echo "   - Go to 'Signing & Capabilities' tab"
echo "   - For EACH target:"
echo "     - Provisioning Profile: Select the matching profile"
echo "     - It should show 'Profile: GigE Virtual Camera Dev' (or Extension Dev)"
echo ""
echo "10. Clean and build:"
echo "    - Product → Clean Build Folder (Shift+Cmd+K)"
echo "    - Product → Build (Cmd+B)"
echo ""
echo "The system extension should now work!"