name: GigEVirtualCamera
options:
  bundleIdPrefix: com.lukechang
  deploymentTarget:
    macOS: "12.3"
  developmentLanguage: en
  
settings:
  DEVELOPMENT_TEAM: S368GH6KF7
  CODE_SIGN_STYLE: Automatic
  
targets:
  GigEVirtualCamera:
    type: application
    platform: macOS
    sources:
      - GigECameraApp
      - path: Shared
        excludes:
          - "*.mm"
          - "*.h"
    dependencies:
      - target: GigECameraExtension
        embed: true
        codeSign: true
        embedInSubfolder: PlugIns
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.lukechang.GigEVirtualCamera
      INFOPLIST_FILE: GigECameraApp/Info.plist
      CODE_SIGN_ENTITLEMENTS: GigECameraApp/GigECamera.entitlements
      SWIFT_VERSION: 5.0
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
      SWIFT_OBJC_BRIDGING_HEADER: Shared/GigEVirtualCamera-Bridging-Header.h
    preBuildScripts:
      - script: |
          if [ -d "${SRCROOT}/Scripts" ]; then
            chmod +x "${SRCROOT}/Scripts/"*.sh
          fi
        name: Make Scripts Executable
        basedOnDependencyAnalysis: false
          
  GigECameraExtension:
    type: app-extension
    platform: macOS
    sources:
      - GigECameraExtension
      - path: Shared
        excludes:
          - "*.mm"
          - "*.h"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.lukechang.GigEVirtualCamera.Extension
      INFOPLIST_FILE: GigECameraExtension/Info.plist
      CODE_SIGN_ENTITLEMENTS: GigECameraExtension/GigECameraExtension.entitlements
      SWIFT_VERSION: 5.0
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
      SWIFT_OBJC_BRIDGING_HEADER: Shared/GigEVirtualCamera-Bridging-Header.h